<?php
	$objectManager  = \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager 	= $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	$basePath 		= $storeManager->getStore()->getBaseUrl();
	$mediaPath 		= $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<style type="text/css">
	/*.admin__fieldset > .admin__field > .admin__field-control{

		float: none;
    width: 285px;
    margin-right: 100px;
    padding-left: 5%;
	}*/
</style>
<!-- <img src="<?= $mediaPath ?>product-view-images/PID_10_ANG_1.svg" alt="Front View" class="viewImage"> -->

<script type="text/javascript">
require(
    [
        'jquery'
    ],
    function ($) {
		$('[data-index="view_image_1"]').children('.admin__field-label').hide();

		$('[data-index="left_view_container"], [data-index="front_view_container"], [data-index="back_view_container"], [data-index="right_view_container"]').children('.admin__field-label').hide();

		$('[data-index="view_image_1"]').children('.admin__field-control').css('width', '275px');
		$('[data-index="view_image_1"]').children('.admin__field-control').css('margin-right', '100px');

		$('[data-index="view_thumb_image_1"]').children('.admin__field-control').css('width', '275px');
		$('[data-index="view_thumb_image_1"]').children('.admin__field-control').css('margin-right', '100px');

		$('[data-index="view_image_1"]').parent().css('margin-left', '15%');
		$('[data-index="view_image_1"]').parent().css('width', '85%');
	}
);
</script>
