<?php
	$objectManager  = \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager 	= $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	$basePath 		= $storeManager->getStore()->getBaseUrl();
	$mediaPath 		= $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<!-- <img src="<?= $mediaPath ?>product-view-images/PID_10_ANG_2.svg" alt="Front View" class="viewImage"> -->

<script type="text/javascript">
require(
    [
        'jquery'
    ],
    function ($) {
		$('[data-index="view_image_2"]').children('.admin__field-label').hide();
		
		$('[data-index="view_image_2"]').children('.admin__field-control').css('width', '275px');
		$('[data-index="view_image_2"]').children('.admin__field-control').css('margin-right', '100px');

		$('[data-index="view_thumb_image_2"]').children('.admin__field-control').css('width', '275px');
		$('[data-index="view_thumb_image_2"]').children('.admin__field-control').css('margin-right', '100px');

		$('[data-index="view_image_2"]').parent().css('margin-left', '15%');
		$('[data-index="view_image_2"]').parent().css('width', '85%');
	}
);
</script>