<?php
	$objectManager  = \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager 	= $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	$basePath 		= $storeManager->getStore()->getBaseUrl();
	$mediaPath 		= $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<style type="text/css">
	.viewImage {
	    position: relative;
		float: left;
		width: 90px;
	    left: 10%;
	}
</style>
<img src="<?= $mediaPath ?>product-view-images/PID_10_THMB_ANG_1.png" alt="Left" style="position: relative;width: 150px;margin-top: -20%;float: left;left: 5%;">

<script type="text/javascript">
	require(
    [
        'jquery'
    ],
    function ($) {
    	// alert('in');
		// alert($(".admin__field").find('.admin__field-label').html());
		// $("#container").find('[data-index="view_image_1"]').chidren().find('.admin__field-label').hide();
	}
);

</script>