<?php
	$objectManager  = \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager 	= $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	$basePath 		= $storeManager->getStore()->getBaseUrl();
	$mediaPath 		= $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<style type="text/css">
	.viewImage {
	    position: relative;
		float: right;
		width: 90px;
	    left: 10%;
	}
</style>
<img src="<?= $mediaPath ?>product-view-images/PID_10_THMB_ANG_1.png" alt="Right" style="position: relative;width: 150px;margin-top: -20%;right: 10%;float: right;">
